trigger:
- main

resources:
  containers:
    - container: python
      image: python:3.8-slim

container: python

steps:
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    chmod +x distrib.sh
    chmod +x run-test.sh
  displayName: 'Make scripts executable'

- script: ./run-test.sh
  displayName: 'Run Tests'

- script: ./distrib.sh
  displayName: 'Build Distribution'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), contains(variables['Build.SourceBranchName'], 'refs/tags/'))

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'), contains(variables['Build.SourceBranchName'], 'refs/tags/'))
# Podríamos reemplazar esta tarea, por el despliegue de la librería en el cluster de PRODUCCION / DEV